# action.yml
name: 'Documentation builder'
description: 'Build the documentation for the project'
inputs:
  repo-toktok:  # id of input
    description: 'GITHUB_TOKEN'
    required: true
outputs:
  outstring: # id of output (variable name)
    description: 'What was barfed by the docker action'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-toktok }}

